### ISSUE TITLE
Implementar o DPM install

### ISSUE THREAD

**Issue by labanca** [splor-mg/atividades#31]
- [Repositório DPM](https://github.com/splor-mg/dpm)
- ler um arquivo datapackage.yaml localmente
- o datapackage.yaml contem uma relação de resources sendo cada um uma fonte de dados com um respectivo datapackage.json.
- baixar os datapackage.json  e os arquivos (resources)
- salvá-los localmente segundo a estrutura descrita no datapackage.yaml
- usar função dereference do frictionless para "abrir" propriedades que referenciem arquivos externos (ex.: schemas/matriz_receita.yaml
![image](https://user-images.githubusercontent.com/7211451/236320757-6d349ce6-52d1-4878-811e-b733a9019458.png)

For the data package

```
name: spreadmart
title: Data mart de dados orçamentários
resources:
  - name: datamart
    path: datamart.db
sources:
  - name: despesa
    title: Despesa Orçamentária
    path: https://dados.mg.gov.br/dataset/despesa
  - name: ppag2023
    title: Plano Plurianual
    path: https://raw.githubusercontent.com/splor-mg/ppag2023-dadosmg/main/datapackage.yaml

```
Running dpm install will create or update the .gitignore file and store fully dereferenced[2](https://splor-mg.github.io/notas/spreadmart-dpm/20230425T104833/#fn2) data packages in their folders:

```
spreadmart/
├── .gitignore
├── datapackage.yaml
└── datapackages
    ├── despesa
    │   ├── data
    │   │   └── data.csv
    │   └── datapackage.json
    └── ppag2023
        ├── data.csv
        └── datapackage.json
```
